/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import javax.swing.JFrame;

/**
 * En la clase-interfaz HospitalServidor implementaremos los sockets para poder
 * cerrar los puestos de vacunación cuando se pida
 * @author Usuario
 */
public class HospitalServidor extends JFrame {

    public HospitalServidor() {
        
        initComponents();
        this.setLocationRelativeTo(null);

        ClienteHilo cl = new ClienteHilo(jTextFieldColaEspera,jTextFieldPaciente,jTextFieldAuxiliarR,jTextFieldSalaDescanso2,jTextFieldSalaDescanso1,jTextFieldauxiliarV,jTextFieldvacunasDisponibles,jTextFieldPuestoV1,jTextFieldPuestoV2,jTextFieldPuestoV3,jTextFieldPuestoV4,jTextFieldPuestoV5,jTextFieldPuestoV6,jTextFieldPuestoV7,jTextFieldPuestoV8,jTextFieldPuestoV9,jTextFieldPuestoV10,jTextFieldPuestoO1,jTextFieldPuestoO2,jTextFieldPuestoO3,jTextFieldPuestoO4,jTextFieldPuestoO5,jTextFieldPuestoO6,jTextFieldPuestoO7,jTextFieldPuestoO8,jTextFieldPuestoO9,jTextFieldPuestoO10,jTextFieldPuestoO11,jTextFieldPuestoO12,jTextFieldPuestoO13,jTextFieldPuestoO14,jTextFieldPuestoO15,jTextFieldPuestoO16,jTextFieldPuestoO17,jTextFieldPuestoO18,jTextFieldPuestoO19,jTextFieldPuestoO20);
        cl.start();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalaVacunacion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPuestoV1 = new javax.swing.JTextField();
        jTextFieldPuestoV2 = new javax.swing.JTextField();
        jTextFieldPuestoV3 = new javax.swing.JTextField();
        jTextFieldPuestoV4 = new javax.swing.JTextField();
        jTextFieldPuestoV5 = new javax.swing.JTextField();
        jTextFieldPuestoV7 = new javax.swing.JTextField();
        jTextFieldPuestoV6 = new javax.swing.JTextField();
        jTextFieldPuestoV8 = new javax.swing.JTextField();
        jTextFieldPuestoV9 = new javax.swing.JTextField();
        jTextFieldPuestoV10 = new javax.swing.JTextField();
        jTextFieldauxiliarV = new javax.swing.JTextField();
        cerrar1 = new javax.swing.JButton();
        cerrar2 = new javax.swing.JButton();
        cerrar3 = new javax.swing.JButton();
        cerrar4 = new javax.swing.JButton();
        cerrar5 = new javax.swing.JButton();
        cerrar6 = new javax.swing.JButton();
        cerrar7 = new javax.swing.JButton();
        cerrar8 = new javax.swing.JButton();
        cerrar9 = new javax.swing.JButton();
        cerrar10 = new javax.swing.JButton();
        jTextFieldvacunasDisponibles = new javax.swing.JTextField();
        recepcion1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jTextFieldColaEspera = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextFieldPaciente = new javax.swing.JTextField();
        jTextFieldAuxiliarR = new javax.swing.JTextField();
        jPanelSalaDescanso = new javax.swing.JPanel();
        jTextFieldSalaDescanso2 = new javax.swing.JTextField();
        jTextFieldSalaDescanso1 = new javax.swing.JTextField();
        jPanelSalaObservacion = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldPuestoO1 = new javax.swing.JTextField();
        jTextFieldPuestoO5 = new javax.swing.JTextField();
        jTextFieldPuestoO10 = new javax.swing.JTextField();
        jTextFieldPuestoO2 = new javax.swing.JTextField();
        jTextFieldPuestoO3 = new javax.swing.JTextField();
        jTextFieldPuestoO6 = new javax.swing.JTextField();
        jTextFieldPuestoO4 = new javax.swing.JTextField();
        jTextFieldPuestoO7 = new javax.swing.JTextField();
        jTextFieldPuestoO8 = new javax.swing.JTextField();
        jTextFieldPuestoO9 = new javax.swing.JTextField();
        jTextFieldPuestoO11 = new javax.swing.JTextField();
        jTextFieldPuestoO13 = new javax.swing.JTextField();
        jTextFieldPuestoO12 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldPuestoO15 = new javax.swing.JTextField();
        jTextFieldPuestoO14 = new javax.swing.JTextField();
        jTextFieldPuestoO16 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldPuestoO17 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldPuestoO18 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldPuestoO19 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldPuestoO20 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSalaVacunacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA DE VACUNACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 1, 18))); // NOI18N
        jPanelSalaVacunacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel7.setText("Puesto 1");
        jPanelSalaVacunacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel8.setText("Puesto 2");
        jPanelSalaVacunacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel9.setText("Puesto 7");
        jPanelSalaVacunacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel10.setText("Puesto 6");
        jPanelSalaVacunacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel11.setText("Puesto 3");
        jPanelSalaVacunacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel12.setText("Puesto 4");
        jPanelSalaVacunacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel13.setText("Puesto 5");
        jPanelSalaVacunacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel14.setText("Puesto 10");
        jPanelSalaVacunacion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel15.setText("Puesto 9");
        jPanelSalaVacunacion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel16.setText("Puesto 8");
        jPanelSalaVacunacion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel17.setText("Auxiliar");
        jPanelSalaVacunacion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel18.setText("Vacunas Disponibles");
        jPanelSalaVacunacion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        jTextFieldPuestoV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV1ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jTextFieldPuestoV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV2ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, -1));

        jTextFieldPuestoV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV3ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 100, -1));

        jTextFieldPuestoV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV4ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 100, -1));

        jTextFieldPuestoV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV5ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 100, -1));

        jTextFieldPuestoV7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV7ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, -1));

        jTextFieldPuestoV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV6ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, -1));

        jTextFieldPuestoV8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV8ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 100, -1));

        jTextFieldPuestoV9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV9ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, -1));

        jTextFieldPuestoV10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV10ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 100, -1));

        jTextFieldauxiliarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldauxiliarVActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldauxiliarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 60, 80, 30));

        cerrar1.setText("Cerrar");
        cerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar1ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        cerrar2.setText("Cerrar");
        cerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar2ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 70, 20));

        cerrar3.setText("Cerrar");
        cerrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar3ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 70, -1));

        cerrar4.setText("Cerrar");
        cerrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar4ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, -1));

        cerrar5.setText("Cerrar");
        cerrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar5ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 70, -1));

        cerrar6.setText("Cerrar");
        cerrar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar6ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 70, -1));

        cerrar7.setText("Cerrar");
        cerrar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar7ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 70, -1));

        cerrar8.setText("Cerrar");
        cerrar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar8ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 70, -1));

        cerrar9.setText("Cerrar");
        cerrar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar9ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 70, -1));

        cerrar10.setText("Cerrar");
        cerrar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar10ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(cerrar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 70, -1));

        jTextFieldvacunasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldvacunasDisponiblesActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldvacunasDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 80, -1));

        recepcion1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECEPCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 18))); // NOI18N
        recepcion1.setForeground(new java.awt.Color(204, 255, 255));

        jLabel40.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel40.setText("Cola de espera");

        jTextFieldColaEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColaEsperaActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel41.setText("Paciente ");

        jLabel42.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel42.setText("Auxiliar");

        jTextFieldPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPacienteActionPerformed(evt);
            }
        });

        jTextFieldAuxiliarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAuxiliarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recepcion1Layout = new javax.swing.GroupLayout(recepcion1);
        recepcion1.setLayout(recepcion1Layout);
        recepcion1Layout.setHorizontalGroup(
            recepcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recepcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recepcion1Layout.createSequentialGroup()
                        .addComponent(jTextFieldColaEspera)
                        .addContainerGap())
                    .addGroup(recepcion1Layout.createSequentialGroup()
                        .addGroup(recepcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(recepcion1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addComponent(jTextFieldPaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(recepcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recepcion1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAuxiliarR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recepcion1Layout.createSequentialGroup()
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))))
            .addGroup(recepcion1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        recepcion1Layout.setVerticalGroup(
            recepcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcion1Layout.createSequentialGroup()
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldColaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(recepcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recepcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAuxiliarR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanelSalaDescanso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA DE DESCANSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 18))); // NOI18N

        jTextFieldSalaDescanso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaDescanso2ActionPerformed(evt);
            }
        });

        jTextFieldSalaDescanso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaDescanso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalaDescansoLayout = new javax.swing.GroupLayout(jPanelSalaDescanso);
        jPanelSalaDescanso.setLayout(jPanelSalaDescansoLayout);
        jPanelSalaDescansoLayout.setHorizontalGroup(
            jPanelSalaDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldSalaDescanso2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
            .addComponent(jTextFieldSalaDescanso1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelSalaDescansoLayout.setVerticalGroup(
            jPanelSalaDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaDescansoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextFieldSalaDescanso1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSalaDescanso2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSalaObservacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA DE OBSERVACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 1, 18))); // NOI18N
        jPanelSalaObservacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel20.setText("Puesto 1");
        jPanelSalaObservacion.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel21.setText("Puesto 2");
        jPanelSalaObservacion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel22.setText("Puesto 3");
        jPanelSalaObservacion.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel23.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel23.setText("Puesto 4");
        jPanelSalaObservacion.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel24.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel24.setText("Puesto 5");
        jPanelSalaObservacion.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel25.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel25.setText("Puesto 6");
        jPanelSalaObservacion.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel26.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel26.setText("Puesto 7");
        jPanelSalaObservacion.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        jLabel27.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel27.setText("Puesto 8");
        jPanelSalaObservacion.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        jLabel28.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel28.setText("Puesto 9");
        jPanelSalaObservacion.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jLabel29.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel29.setText("Puesto 10");
        jPanelSalaObservacion.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel30.setText("Puesto 11");
        jPanelSalaObservacion.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, -1));

        jLabel31.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel31.setText("Puesto 12");
        jPanelSalaObservacion.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel32.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel32.setText("Puesto 15");
        jPanelSalaObservacion.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel34.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel34.setText("Puesto 13");
        jPanelSalaObservacion.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel35.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel35.setText("Puesto 14");
        jPanelSalaObservacion.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, -1));

        jTextFieldPuestoO16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoO16ActionPerformed(evt);
            }
        });
        jPanelSalaObservacion.add(jTextFieldPuestoO16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 80, -1));

        jLabel33.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel33.setText("Puesto 16");
        jPanelSalaObservacion.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 80, -1));

        jLabel36.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel36.setText("Puesto 17");
        jPanelSalaObservacion.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 80, -1));

        jLabel37.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel37.setText("Puesto 18");
        jPanelSalaObservacion.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 80, -1));

        jLabel38.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel38.setText("Puesto 19");
        jPanelSalaObservacion.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, -1));

        jLabel39.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel39.setText("Puesto 20");
        jPanelSalaObservacion.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO20, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSalaVacunacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recepcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSalaDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelSalaObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recepcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSalaDescanso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelSalaVacunacion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanelSalaObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPuestoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV1ActionPerformed

    private void jTextFieldPuestoV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV2ActionPerformed

    private void jTextFieldPuestoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV3ActionPerformed

    private void jTextFieldPuestoV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV4ActionPerformed

    private void jTextFieldPuestoV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV5ActionPerformed

    private void jTextFieldPuestoV7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV7ActionPerformed

    private void jTextFieldPuestoV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV6ActionPerformed

    private void jTextFieldPuestoV8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV8ActionPerformed

    private void jTextFieldPuestoV9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV9ActionPerformed

    private void jTextFieldPuestoV10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV10ActionPerformed

    private void jTextFieldauxiliarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldauxiliarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldauxiliarVActionPerformed

    private void jTextFieldvacunasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldvacunasDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldvacunasDisponiblesActionPerformed

    /**
     * Los botones de cerrar puesto llamarán a la salida correspondiente del servidor
     * para frenar su ejecución y mandar a los sanitarios a la sala de descanso. 
     * Los siguientes 9 métodos cumplen la misma función, cambiando el puesto. 
     */
    private void cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar1ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(5);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
        

    }//GEN-LAST:event_cerrar1ActionPerformed

    private void cerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar2ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(6);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar2ActionPerformed

    private void cerrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar3ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(7);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar3ActionPerformed

    private void cerrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar4ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(8);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar4ActionPerformed

    private void cerrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar5ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(9);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar5ActionPerformed

    private void cerrar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar6ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(10);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar6ActionPerformed

    private void cerrar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar7ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(11);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar7ActionPerformed

    private void cerrar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar8ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(12);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar8ActionPerformed

    private void cerrar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar9ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(13);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión

        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar9ActionPerformed

    private void cerrar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar10ActionPerformed
        Socket servi;
        DataInputStream entrada;
        DataOutputStream salida;

        try {
            servi = new Socket(InetAddress.getLocalHost(), 30000);
            entrada = new DataInputStream(servi.getInputStream());
            salida = new DataOutputStream(servi.getOutputStream());

            salida.writeInt(14);

            entrada.close(); //Cerramos los flujos de entrada y salida
            salida.close();
            servi.close(); //Cerramos la conexión
            
        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cerrar10ActionPerformed

    private void jTextFieldColaEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColaEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColaEsperaActionPerformed

    private void jTextFieldPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPacienteActionPerformed

    private void jTextFieldAuxiliarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAuxiliarRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAuxiliarRActionPerformed

    private void jTextFieldSalaDescanso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaDescanso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaDescanso2ActionPerformed

    private void jTextFieldSalaDescanso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaDescanso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaDescanso1ActionPerformed

    private void jTextFieldPuestoO16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoO16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoO16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar1;
    private javax.swing.JButton cerrar10;
    private javax.swing.JButton cerrar2;
    private javax.swing.JButton cerrar3;
    private javax.swing.JButton cerrar4;
    private javax.swing.JButton cerrar5;
    private javax.swing.JButton cerrar6;
    private javax.swing.JButton cerrar7;
    private javax.swing.JButton cerrar8;
    private javax.swing.JButton cerrar9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelSalaDescanso;
    private javax.swing.JPanel jPanelSalaObservacion;
    private javax.swing.JPanel jPanelSalaVacunacion;
    private javax.swing.JTextField jTextFieldAuxiliarR;
    private javax.swing.JTextField jTextFieldColaEspera;
    private javax.swing.JTextField jTextFieldPaciente;
    private javax.swing.JTextField jTextFieldPuestoO1;
    private javax.swing.JTextField jTextFieldPuestoO10;
    private javax.swing.JTextField jTextFieldPuestoO11;
    private javax.swing.JTextField jTextFieldPuestoO12;
    private javax.swing.JTextField jTextFieldPuestoO13;
    private javax.swing.JTextField jTextFieldPuestoO14;
    private javax.swing.JTextField jTextFieldPuestoO15;
    private javax.swing.JTextField jTextFieldPuestoO16;
    private javax.swing.JTextField jTextFieldPuestoO17;
    private javax.swing.JTextField jTextFieldPuestoO18;
    private javax.swing.JTextField jTextFieldPuestoO19;
    private javax.swing.JTextField jTextFieldPuestoO2;
    private javax.swing.JTextField jTextFieldPuestoO20;
    private javax.swing.JTextField jTextFieldPuestoO3;
    private javax.swing.JTextField jTextFieldPuestoO4;
    private javax.swing.JTextField jTextFieldPuestoO5;
    private javax.swing.JTextField jTextFieldPuestoO6;
    private javax.swing.JTextField jTextFieldPuestoO7;
    private javax.swing.JTextField jTextFieldPuestoO8;
    private javax.swing.JTextField jTextFieldPuestoO9;
    private javax.swing.JTextField jTextFieldPuestoV1;
    private javax.swing.JTextField jTextFieldPuestoV10;
    private javax.swing.JTextField jTextFieldPuestoV2;
    private javax.swing.JTextField jTextFieldPuestoV3;
    private javax.swing.JTextField jTextFieldPuestoV4;
    private javax.swing.JTextField jTextFieldPuestoV5;
    private javax.swing.JTextField jTextFieldPuestoV6;
    private javax.swing.JTextField jTextFieldPuestoV7;
    private javax.swing.JTextField jTextFieldPuestoV8;
    private javax.swing.JTextField jTextFieldPuestoV9;
    private javax.swing.JTextField jTextFieldSalaDescanso1;
    private javax.swing.JTextField jTextFieldSalaDescanso2;
    private javax.swing.JTextField jTextFieldauxiliarV;
    private javax.swing.JTextField jTextFieldvacunasDisponibles;
    private javax.swing.JPanel recepcion1;
    // End of variables declaration//GEN-END:variables
}
