/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import parte1.*;

/**
 * InterfazHospital estará a cargo de manejar todo lo relacionado con la interfaz 
 * del programa. Creará los hilos y los ejecutará
 * @author Usuario
 */
public class InterfazHospital extends javax.swing.JFrame {

    public InterfazHospital() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);// centra la interfaz

        
        EscrituraTexto et = new EscrituraTexto();
        SalaDescanso salaDescanso = new SalaDescanso(jTextFieldSalaDescanso1, jTextFieldSalaDescanso2, et);
        SalaVacunacion salaVacunacion = new SalaVacunacion(jTextFieldPuestoV1, jTextFieldPuestoV2, jTextFieldPuestoV3, jTextFieldPuestoV4, jTextFieldPuestoV5, jTextFieldPuestoV6, jTextFieldPuestoV7, jTextFieldPuestoV8, jTextFieldPuestoV9, jTextFieldPuestoV10, jTextFieldauxiliarV, jTextFieldvacunasDisponibles, et);
        SalaObservacion salaObservacion = new SalaObservacion(jTextFieldPuestoO1, jTextFieldPuestoO2, jTextFieldPuestoO3, jTextFieldPuestoO4, jTextFieldPuestoO5, jTextFieldPuestoO6, jTextFieldPuestoO7, jTextFieldPuestoO8, jTextFieldPuestoO9, jTextFieldPuestoO10, jTextFieldPuestoO11, jTextFieldPuestoO12, jTextFieldPuestoO13, jTextFieldPuestoO14, jTextFieldPuestoO15, jTextFieldPuestoO16, jTextFieldPuestoO17, jTextFieldPuestoO18, jTextFieldPuestoO19, jTextFieldPuestoO20, et);
        Recepcion recepcion = new Recepcion(jTextFieldColaEspera, jTextFieldPaciente, jTextFieldAuxiliarR, et);
        Hospital hospital = new Hospital(recepcion, salaDescanso, salaObservacion, salaVacunacion);
        
        
        for (int i = 1; i < 21; i++) {
            Sanitario s = new Sanitario(i, hospital);
           
            s.start();
        }

        for (int i = 1; i < 3; i++) {
            Auxiliar a = new Auxiliar(i, hospital);
            a.start();
        }

        CreaPacientes p = new CreaPacientes(hospital, et);
        p.start();
        
        
        ServidorHospital sh = new ServidorHospital(hospital);
        sh.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recepcion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldColaEspera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPaciente = new javax.swing.JTextField();
        jTextFieldAuxiliarR = new javax.swing.JTextField();
        jPanelSalaDescanso = new javax.swing.JPanel();
        jTextFieldSalaDescanso2 = new javax.swing.JTextField();
        jTextFieldSalaDescanso1 = new javax.swing.JTextField();
        jPanelSalaVacunacion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPuestoV1 = new javax.swing.JTextField();
        jTextFieldPuestoV2 = new javax.swing.JTextField();
        jTextFieldPuestoV3 = new javax.swing.JTextField();
        jTextFieldPuestoV4 = new javax.swing.JTextField();
        jTextFieldPuestoV5 = new javax.swing.JTextField();
        jTextFieldPuestoV7 = new javax.swing.JTextField();
        jTextFieldPuestoV6 = new javax.swing.JTextField();
        jTextFieldPuestoV8 = new javax.swing.JTextField();
        jTextFieldPuestoV9 = new javax.swing.JTextField();
        jTextFieldPuestoV10 = new javax.swing.JTextField();
        jTextFieldauxiliarV = new javax.swing.JTextField();
        jTextFieldvacunasDisponibles = new javax.swing.JTextField();
        jPanelSalaObservacion = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldPuestoO1 = new javax.swing.JTextField();
        jTextFieldPuestoO5 = new javax.swing.JTextField();
        jTextFieldPuestoO10 = new javax.swing.JTextField();
        jTextFieldPuestoO2 = new javax.swing.JTextField();
        jTextFieldPuestoO3 = new javax.swing.JTextField();
        jTextFieldPuestoO6 = new javax.swing.JTextField();
        jTextFieldPuestoO4 = new javax.swing.JTextField();
        jTextFieldPuestoO7 = new javax.swing.JTextField();
        jTextFieldPuestoO8 = new javax.swing.JTextField();
        jTextFieldPuestoO9 = new javax.swing.JTextField();
        jTextFieldPuestoO11 = new javax.swing.JTextField();
        jTextFieldPuestoO13 = new javax.swing.JTextField();
        jTextFieldPuestoO12 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldPuestoO15 = new javax.swing.JTextField();
        jTextFieldPuestoO14 = new javax.swing.JTextField();
        jTextFieldPuestoO16 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldPuestoO17 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldPuestoO18 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldPuestoO19 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldPuestoO20 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recepcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECEPCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 18))); // NOI18N
        recepcion.setForeground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel2.setText("Cola de espera");

        jTextFieldColaEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColaEsperaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel3.setText("Paciente ");

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel4.setText("Auxiliar");

        jTextFieldPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPacienteActionPerformed(evt);
            }
        });

        jTextFieldAuxiliarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAuxiliarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recepcionLayout = new javax.swing.GroupLayout(recepcion);
        recepcion.setLayout(recepcionLayout);
        recepcionLayout.setHorizontalGroup(
            recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recepcionLayout.createSequentialGroup()
                        .addComponent(jTextFieldColaEspera)
                        .addContainerGap())
                    .addGroup(recepcionLayout.createSequentialGroup()
                        .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(recepcionLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addComponent(jTextFieldPaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recepcionLayout.createSequentialGroup()
                                .addComponent(jTextFieldAuxiliarR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recepcionLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))))
            .addGroup(recepcionLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        recepcionLayout.setVerticalGroup(
            recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldColaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAuxiliarR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanelSalaDescanso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA DE DESCANSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 18))); // NOI18N

        jTextFieldSalaDescanso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaDescanso2ActionPerformed(evt);
            }
        });

        jTextFieldSalaDescanso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaDescanso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalaDescansoLayout = new javax.swing.GroupLayout(jPanelSalaDescanso);
        jPanelSalaDescanso.setLayout(jPanelSalaDescansoLayout);
        jPanelSalaDescansoLayout.setHorizontalGroup(
            jPanelSalaDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldSalaDescanso2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
            .addComponent(jTextFieldSalaDescanso1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelSalaDescansoLayout.setVerticalGroup(
            jPanelSalaDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaDescansoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextFieldSalaDescanso1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSalaDescanso2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSalaVacunacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA DE VACUNACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 0, 18))); // NOI18N
        jPanelSalaVacunacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel7.setText("Puesto 1");
        jPanelSalaVacunacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel8.setText("Puesto 2");
        jPanelSalaVacunacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel9.setText("Puesto 7");
        jPanelSalaVacunacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel10.setText("Puesto 6");
        jPanelSalaVacunacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel11.setText("Puesto 3");
        jPanelSalaVacunacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel12.setText("Puesto 4");
        jPanelSalaVacunacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel13.setText("Puesto 5");
        jPanelSalaVacunacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel14.setText("Puesto 10");
        jPanelSalaVacunacion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel15.setText("Puesto 9");
        jPanelSalaVacunacion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel16.setText("Puesto 8");
        jPanelSalaVacunacion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel17.setText("Auxiliar");
        jPanelSalaVacunacion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 70, 20));

        jLabel18.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel18.setText("Vacunas Disponibles");
        jPanelSalaVacunacion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, -1, -1));

        jTextFieldPuestoV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV1ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jTextFieldPuestoV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV2ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 100, -1));

        jTextFieldPuestoV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV3ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 100, -1));

        jTextFieldPuestoV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV4ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 100, -1));

        jTextFieldPuestoV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV5ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 100, -1));

        jTextFieldPuestoV7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV7ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, -1));

        jTextFieldPuestoV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV6ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jTextFieldPuestoV8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV8ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 100, -1));

        jTextFieldPuestoV9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV9ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 100, -1));

        jTextFieldPuestoV10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV10ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 100, -1));

        jTextFieldauxiliarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldauxiliarVActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldauxiliarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 100, 30));

        jTextFieldvacunasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldvacunasDisponiblesActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldvacunasDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 100, -1));

        jPanelSalaObservacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA DE OBSERVACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Stencil", 1, 18))); // NOI18N
        jPanelSalaObservacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel20.setText("Puesto 1");
        jPanelSalaObservacion.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel21.setText("Puesto 2");
        jPanelSalaObservacion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel22.setText("Puesto 3");
        jPanelSalaObservacion.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel23.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel23.setText("Puesto 4");
        jPanelSalaObservacion.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel24.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel24.setText("Puesto 5");
        jPanelSalaObservacion.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel25.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel25.setText("Puesto 6");
        jPanelSalaObservacion.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel26.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel26.setText("Puesto 7");
        jPanelSalaObservacion.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        jLabel27.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel27.setText("Puesto 8");
        jPanelSalaObservacion.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        jLabel28.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel28.setText("Puesto 9");
        jPanelSalaObservacion.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jLabel29.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel29.setText("Puesto 10");
        jPanelSalaObservacion.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel30.setText("Puesto 11");
        jPanelSalaObservacion.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, -1));

        jLabel31.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel31.setText("Puesto 12");
        jPanelSalaObservacion.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel32.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel32.setText("Puesto 15");
        jPanelSalaObservacion.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel34.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel34.setText("Puesto 13");
        jPanelSalaObservacion.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel35.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel35.setText("Puesto 14");
        jPanelSalaObservacion.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 80, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, -1));

        jTextFieldPuestoO16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoO16ActionPerformed(evt);
            }
        });
        jPanelSalaObservacion.add(jTextFieldPuestoO16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 80, -1));

        jLabel33.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel33.setText("Puesto 16");
        jPanelSalaObservacion.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 80, -1));

        jLabel36.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel36.setText("Puesto 17");
        jPanelSalaObservacion.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 80, -1));

        jLabel37.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel37.setText("Puesto 18");
        jPanelSalaObservacion.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 80, -1));

        jLabel38.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel38.setText("Puesto 19");
        jPanelSalaObservacion.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, -1));

        jLabel39.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        jLabel39.setText("Puesto 20");
        jPanelSalaObservacion.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO20, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 80, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(recepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanelSalaDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
            .addComponent(jPanelSalaObservacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSalaVacunacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recepcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSalaDescanso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanelSalaVacunacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSalaObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 64, -1, -1));

        jLabel40.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 0, 255));
        jLabel40.setText("HOSPITAL");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 210, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldColaEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColaEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColaEsperaActionPerformed

    private void jTextFieldPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPacienteActionPerformed

    private void jTextFieldAuxiliarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAuxiliarRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAuxiliarRActionPerformed

    private void jTextFieldSalaDescanso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaDescanso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaDescanso2ActionPerformed

    private void jTextFieldPuestoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV1ActionPerformed

    private void jTextFieldPuestoV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV2ActionPerformed

    private void jTextFieldPuestoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV3ActionPerformed

    private void jTextFieldPuestoV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV4ActionPerformed

    private void jTextFieldPuestoV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV5ActionPerformed

    private void jTextFieldPuestoV7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV7ActionPerformed

    private void jTextFieldPuestoV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV6ActionPerformed

    private void jTextFieldPuestoV8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV8ActionPerformed

    private void jTextFieldPuestoV9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV9ActionPerformed

    private void jTextFieldPuestoV10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV10ActionPerformed

    private void jTextFieldauxiliarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldauxiliarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldauxiliarVActionPerformed

    private void jTextFieldPuestoO16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoO16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoO16ActionPerformed

    private void jTextFieldvacunasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldvacunasDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldvacunasDisponiblesActionPerformed

    private void jTextFieldSalaDescanso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaDescanso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaDescanso1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazHospital().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazHospital.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSalaDescanso;
    private javax.swing.JPanel jPanelSalaObservacion;
    private javax.swing.JPanel jPanelSalaVacunacion;
    private javax.swing.JTextField jTextFieldAuxiliarR;
    private javax.swing.JTextField jTextFieldColaEspera;
    private javax.swing.JTextField jTextFieldPaciente;
    private javax.swing.JTextField jTextFieldPuestoO1;
    private javax.swing.JTextField jTextFieldPuestoO10;
    private javax.swing.JTextField jTextFieldPuestoO11;
    private javax.swing.JTextField jTextFieldPuestoO12;
    private javax.swing.JTextField jTextFieldPuestoO13;
    private javax.swing.JTextField jTextFieldPuestoO14;
    private javax.swing.JTextField jTextFieldPuestoO15;
    private javax.swing.JTextField jTextFieldPuestoO16;
    private javax.swing.JTextField jTextFieldPuestoO17;
    private javax.swing.JTextField jTextFieldPuestoO18;
    private javax.swing.JTextField jTextFieldPuestoO19;
    private javax.swing.JTextField jTextFieldPuestoO2;
    private javax.swing.JTextField jTextFieldPuestoO20;
    private javax.swing.JTextField jTextFieldPuestoO3;
    private javax.swing.JTextField jTextFieldPuestoO4;
    private javax.swing.JTextField jTextFieldPuestoO5;
    private javax.swing.JTextField jTextFieldPuestoO6;
    private javax.swing.JTextField jTextFieldPuestoO7;
    private javax.swing.JTextField jTextFieldPuestoO8;
    private javax.swing.JTextField jTextFieldPuestoO9;
    private javax.swing.JTextField jTextFieldPuestoV1;
    private javax.swing.JTextField jTextFieldPuestoV10;
    private javax.swing.JTextField jTextFieldPuestoV2;
    private javax.swing.JTextField jTextFieldPuestoV3;
    private javax.swing.JTextField jTextFieldPuestoV4;
    private javax.swing.JTextField jTextFieldPuestoV5;
    private javax.swing.JTextField jTextFieldPuestoV6;
    private javax.swing.JTextField jTextFieldPuestoV7;
    private javax.swing.JTextField jTextFieldPuestoV8;
    private javax.swing.JTextField jTextFieldPuestoV9;
    private javax.swing.JTextField jTextFieldSalaDescanso1;
    private javax.swing.JTextField jTextFieldSalaDescanso2;
    private javax.swing.JTextField jTextFieldauxiliarV;
    private javax.swing.JTextField jTextFieldvacunasDisponibles;
    private javax.swing.JPanel recepcion;
    // End of variables declaration//GEN-END:variables
}
