/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import parte1.*;

public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() throws IOException {
        initComponents();
        EscrituraTexto et = new EscrituraTexto();
        SalaDescanso salaDescanso = new SalaDescanso(jTextFieldSalaDescanso1, jTextFieldSalaDescanso2);
        SalaVacunacion salaVacunacion = new SalaVacunacion(jTextFieldPuestoV1, jTextFieldPuestoV2, jTextFieldPuestoV3, jTextFieldPuestoV4, jTextFieldPuestoV5, jTextFieldPuestoV6, jTextFieldPuestoV7, jTextFieldPuestoV8, jTextFieldPuestoV9, jTextFieldPuestoV10, jTextFieldauxiliarV, jTextFieldvacunasDisponibles, et);
        SalaObservacion salaObservacion = new SalaObservacion(jTextFieldPuestoO1, jTextFieldPuestoO2, jTextFieldPuestoO3, jTextFieldPuestoO4, jTextFieldPuestoO5, jTextFieldPuestoO6, jTextFieldPuestoO7, jTextFieldPuestoO8, jTextFieldPuestoO9, jTextFieldPuestoO10, jTextFieldPuestoO11, jTextFieldPuestoO12, jTextFieldPuestoO13, jTextFieldPuestoO14, jTextFieldPuestoO15, jTextFieldPuestoO16, jTextFieldPuestoO17, jTextFieldPuestoO18, jTextFieldPuestoO19, jTextFieldPuestoO20);
        Recepcion recepcion = new Recepcion(jTextFieldColaEspera, jTextFieldPaciente, jTextFieldAuxiliarR, et);
        Hospital hospital = new Hospital(recepcion, salaDescanso, salaObservacion, salaVacunacion);
        
        
        for (int i = 1; i < 21; i++) {
            Sanitario s = new Sanitario(i, hospital);
           
            s.start();
        }

        for (int i = 1; i < 3; i++) {
            Auxiliar a = new Auxiliar(i, hospital);
            a.start();
        }

        CreaPacientes p = new CreaPacientes(hospital);
        p.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recepcion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldColaEspera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPaciente = new javax.swing.JTextField();
        jTextFieldAuxiliarR = new javax.swing.JTextField();
        jPanelSalaDescanso = new javax.swing.JPanel();
        jTextFieldSalaDescanso2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSalaDescanso1 = new javax.swing.JTextField();
        jPanelSalaVacunacion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPuestoV1 = new javax.swing.JTextField();
        jTextFieldPuestoV2 = new javax.swing.JTextField();
        jTextFieldPuestoV3 = new javax.swing.JTextField();
        jTextFieldPuestoV4 = new javax.swing.JTextField();
        jTextFieldPuestoV5 = new javax.swing.JTextField();
        jTextFieldPuestoV7 = new javax.swing.JTextField();
        jTextFieldPuestoV6 = new javax.swing.JTextField();
        jTextFieldPuestoV8 = new javax.swing.JTextField();
        jTextFieldPuestoV9 = new javax.swing.JTextField();
        jTextFieldPuestoV10 = new javax.swing.JTextField();
        jTextFieldauxiliarV = new javax.swing.JTextField();
        jTextFieldvacunasDisponibles = new javax.swing.JTextField();
        jPanelSalaObservacion = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldPuestoO1 = new javax.swing.JTextField();
        jTextFieldPuestoO5 = new javax.swing.JTextField();
        jTextFieldPuestoO10 = new javax.swing.JTextField();
        jTextFieldPuestoO2 = new javax.swing.JTextField();
        jTextFieldPuestoO3 = new javax.swing.JTextField();
        jTextFieldPuestoO6 = new javax.swing.JTextField();
        jTextFieldPuestoO4 = new javax.swing.JTextField();
        jTextFieldPuestoO7 = new javax.swing.JTextField();
        jTextFieldPuestoO8 = new javax.swing.JTextField();
        jTextFieldPuestoO9 = new javax.swing.JTextField();
        jTextFieldPuestoO11 = new javax.swing.JTextField();
        jTextFieldPuestoO13 = new javax.swing.JTextField();
        jTextFieldPuestoO12 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldPuestoO15 = new javax.swing.JTextField();
        jTextFieldPuestoO16 = new javax.swing.JTextField();
        jTextFieldPuestoO17 = new javax.swing.JTextField();
        jTextFieldPuestoO14 = new javax.swing.JTextField();
        jTextFieldPuestoO18 = new javax.swing.JTextField();
        jTextFieldPuestoO19 = new javax.swing.JTextField();
        jTextFieldPuestoO20 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" RECEPCIÓN");

        jLabel2.setText("Cola de espera");

        jTextFieldColaEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColaEsperaActionPerformed(evt);
            }
        });

        jLabel3.setText("Paciente ");

        jLabel4.setText("Auxiliar");

        jTextFieldPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPacienteActionPerformed(evt);
            }
        });

        jTextFieldAuxiliarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAuxiliarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recepcionLayout = new javax.swing.GroupLayout(recepcion);
        recepcion.setLayout(recepcionLayout);
        recepcionLayout.setHorizontalGroup(
            recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionLayout.createSequentialGroup()
                .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recepcionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldColaEspera))
                    .addGroup(recepcionLayout.createSequentialGroup()
                        .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(recepcionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(recepcionLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(recepcionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(89, 89, 89)
                        .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(recepcionLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addComponent(jTextFieldAuxiliarR))))
                .addContainerGap())
        );
        recepcionLayout.setVerticalGroup(
            recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldColaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAuxiliarR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jTextFieldSalaDescanso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaDescanso2ActionPerformed(evt);
            }
        });

        jLabel5.setText("SALA DE DESCANSO");

        jTextFieldSalaDescanso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaDescanso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalaDescansoLayout = new javax.swing.GroupLayout(jPanelSalaDescanso);
        jPanelSalaDescanso.setLayout(jPanelSalaDescansoLayout);
        jPanelSalaDescansoLayout.setHorizontalGroup(
            jPanelSalaDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaDescansoLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTextFieldSalaDescanso2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTextFieldSalaDescanso1)
        );
        jPanelSalaDescansoLayout.setVerticalGroup(
            jPanelSalaDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaDescansoLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSalaDescanso1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSalaDescanso2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSalaVacunacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("SALA DE VACUNACIÓN");
        jPanelSalaVacunacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 0, -1, 24));

        jLabel7.setText("Puesto 1");
        jPanelSalaVacunacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel8.setText("Puesto 2");
        jPanelSalaVacunacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel9.setText("Puesto 7");
        jPanelSalaVacunacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel10.setText("Puesto 6");
        jPanelSalaVacunacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel11.setText("Puesto 3");
        jPanelSalaVacunacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel12.setText("Puesto 4");
        jPanelSalaVacunacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel13.setText("Puesto 5");
        jPanelSalaVacunacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jLabel14.setText("Puesto 10");
        jPanelSalaVacunacion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jLabel15.setText("Puesto 9");
        jPanelSalaVacunacion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel16.setText("Puesto 8");
        jPanelSalaVacunacion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel17.setText("Auxiliar");
        jPanelSalaVacunacion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 35, -1, -1));

        jLabel18.setText("Vacunas Disponibles");
        jPanelSalaVacunacion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 95, -1, -1));

        jTextFieldPuestoV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV1ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jTextFieldPuestoV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV2ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, -1));

        jTextFieldPuestoV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV3ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 100, -1));

        jTextFieldPuestoV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV4ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 100, -1));

        jTextFieldPuestoV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV5ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 100, -1));

        jTextFieldPuestoV7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV7ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 100, -1));

        jTextFieldPuestoV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV6ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jTextFieldPuestoV8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV8ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 100, -1));

        jTextFieldPuestoV9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV9ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 100, -1));

        jTextFieldPuestoV10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoV10ActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldPuestoV10, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 110, 100, -1));

        jTextFieldauxiliarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldauxiliarVActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldauxiliarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 55, 69, -1));

        jTextFieldvacunasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldvacunasDisponiblesActionPerformed(evt);
            }
        });
        jPanelSalaVacunacion.add(jTextFieldvacunasDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 115, 77, -1));

        jPanelSalaObservacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("SALA DE OBSERVACIÓN");
        jPanelSalaObservacion.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 0, 128, 27));

        jLabel20.setText("Puesto 1");
        jPanelSalaObservacion.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel21.setText("Puesto 2");
        jPanelSalaObservacion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel22.setText("Puesto 3");
        jPanelSalaObservacion.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel23.setText("Puesto 4");
        jPanelSalaObservacion.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel24.setText("Puesto 5");
        jPanelSalaObservacion.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel25.setText("Puesto 6");
        jPanelSalaObservacion.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel26.setText("Puesto 7");
        jPanelSalaObservacion.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel27.setText("Puesto 8");
        jPanelSalaObservacion.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        jLabel28.setText("Puesto 9");
        jPanelSalaObservacion.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel29.setText("Puesto 10");
        jPanelSalaObservacion.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jLabel30.setText("Puesto 11");
        jPanelSalaObservacion.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 55, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 50, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 60, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 55, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 50, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 50, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 56, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 60, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 56, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 57, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 50, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 60, -1));

        jLabel31.setText("Puesto 12");
        jPanelSalaObservacion.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 118, -1, -1));

        jLabel32.setText("Puesto 15");
        jPanelSalaObservacion.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel33.setText("Puesto 16");
        jPanelSalaObservacion.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 118, -1, -1));

        jLabel34.setText("Puesto 13");
        jPanelSalaObservacion.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 118, -1, -1));

        jLabel35.setText("Puesto 14");
        jPanelSalaObservacion.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel36.setText("Puesto 17");
        jPanelSalaObservacion.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jLabel37.setText("Puesto 18");
        jPanelSalaObservacion.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel38.setText("Puesto 19");
        jPanelSalaObservacion.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel39.setText("Puesto 20");
        jPanelSalaObservacion.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 50, -1));

        jTextFieldPuestoO16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuestoO16ActionPerformed(evt);
            }
        });
        jPanelSalaObservacion.add(jTextFieldPuestoO16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 50, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 60, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 48, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 62, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 58, -1));
        jPanelSalaObservacion.add(jTextFieldPuestoO20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 60, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(recepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanelSalaDescanso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelSalaVacunacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSalaObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelSalaDescanso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recepcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSalaVacunacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSalaObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 64, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldColaEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColaEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColaEsperaActionPerformed

    private void jTextFieldPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPacienteActionPerformed

    private void jTextFieldAuxiliarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAuxiliarRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAuxiliarRActionPerformed

    private void jTextFieldSalaDescanso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaDescanso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaDescanso2ActionPerformed

    private void jTextFieldPuestoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV1ActionPerformed

    private void jTextFieldPuestoV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV2ActionPerformed

    private void jTextFieldPuestoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV3ActionPerformed

    private void jTextFieldPuestoV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV4ActionPerformed

    private void jTextFieldPuestoV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV5ActionPerformed

    private void jTextFieldPuestoV7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV7ActionPerformed

    private void jTextFieldPuestoV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV6ActionPerformed

    private void jTextFieldPuestoV8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV8ActionPerformed

    private void jTextFieldPuestoV9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV9ActionPerformed

    private void jTextFieldPuestoV10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoV10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoV10ActionPerformed

    private void jTextFieldauxiliarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldauxiliarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldauxiliarVActionPerformed

    private void jTextFieldPuestoO16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuestoO16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuestoO16ActionPerformed

    private void jTextFieldvacunasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldvacunasDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldvacunasDisponiblesActionPerformed

    private void jTextFieldSalaDescanso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaDescanso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaDescanso1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new interfaz().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSalaDescanso;
    private javax.swing.JPanel jPanelSalaObservacion;
    private javax.swing.JPanel jPanelSalaVacunacion;
    private javax.swing.JTextField jTextFieldAuxiliarR;
    private javax.swing.JTextField jTextFieldColaEspera;
    private javax.swing.JTextField jTextFieldPaciente;
    private javax.swing.JTextField jTextFieldPuestoO1;
    private javax.swing.JTextField jTextFieldPuestoO10;
    private javax.swing.JTextField jTextFieldPuestoO11;
    private javax.swing.JTextField jTextFieldPuestoO12;
    private javax.swing.JTextField jTextFieldPuestoO13;
    private javax.swing.JTextField jTextFieldPuestoO14;
    private javax.swing.JTextField jTextFieldPuestoO15;
    private javax.swing.JTextField jTextFieldPuestoO16;
    private javax.swing.JTextField jTextFieldPuestoO17;
    private javax.swing.JTextField jTextFieldPuestoO18;
    private javax.swing.JTextField jTextFieldPuestoO19;
    private javax.swing.JTextField jTextFieldPuestoO2;
    private javax.swing.JTextField jTextFieldPuestoO20;
    private javax.swing.JTextField jTextFieldPuestoO3;
    private javax.swing.JTextField jTextFieldPuestoO4;
    private javax.swing.JTextField jTextFieldPuestoO5;
    private javax.swing.JTextField jTextFieldPuestoO6;
    private javax.swing.JTextField jTextFieldPuestoO7;
    private javax.swing.JTextField jTextFieldPuestoO8;
    private javax.swing.JTextField jTextFieldPuestoO9;
    private javax.swing.JTextField jTextFieldPuestoV1;
    private javax.swing.JTextField jTextFieldPuestoV10;
    private javax.swing.JTextField jTextFieldPuestoV2;
    private javax.swing.JTextField jTextFieldPuestoV3;
    private javax.swing.JTextField jTextFieldPuestoV4;
    private javax.swing.JTextField jTextFieldPuestoV5;
    private javax.swing.JTextField jTextFieldPuestoV6;
    private javax.swing.JTextField jTextFieldPuestoV7;
    private javax.swing.JTextField jTextFieldPuestoV8;
    private javax.swing.JTextField jTextFieldPuestoV9;
    private javax.swing.JTextField jTextFieldSalaDescanso1;
    private javax.swing.JTextField jTextFieldSalaDescanso2;
    private javax.swing.JTextField jTextFieldauxiliarV;
    private javax.swing.JTextField jTextFieldvacunasDisponibles;
    private javax.swing.JPanel recepcion;
    // End of variables declaration//GEN-END:variables
}
